### ISSUE TITLE
Revision: Explain statistical decisions re-Cox tests

### ISSUE THREAD

**Issue by sjspielman** [AlexsLemonade/OpenPBTA-manuscript#371]
One comment from reviewers suggested we might have used one overall histology variable as a factor in Cox tests, instead of for example HGG-only samples being modeled where the histology variable is binary `yes` or `no` for HGG histology.

In addition to the reviewer response itself, we might wish to clarify in the text why we took this approach, which involves a discussion of how categorical predictors are handled in Cox regression itself.

**Comment by jharenza** [comment]
I think this is already addressed in methods:

```
Next, we used multivariate Cox (proportional hazards) regression analysis [@doi:10.1111/j.2517-6161.1972.tb00899.x] to model the following: a) `tp53 scores + telomerase scores + extent of tumor resection + LGG group + HGG group`, in which `tp53 scores` and `telomerase scores` are numeric, `extent of tumor resection` is categorical, and `LGG group` and `HGG group` are binary variables indicating whether the sample is in either broad histology grouping, b) `tp53 scores + telomerase scores + extent of tumor resection` for each `cancer_group` with an N>=3 deceased patients (DIPG, DMG, HGG, MB, and EPN), and c) `quantiseq cell type fractions + CD274 expression + extent of tumor resection` for each `cancer_group` with an N>=3 deceased patients (DIPG, DMG, HGG, MB, and EPN), in which `quantiseq cell type fractions` and `CD274 expression` are numeric.
```

@sjspielman was there more you think we should add?

**Comment by sjspielman** [comment]
I think what we have is fine and we can focus on the response to reviewers for this one. I guess a different thing we _could_ have done is a diff variable with three categories - LGAT, HGAT, or other, but I don't see how that would have affected results since the problem remains that we can't do histology itself as a predictor since it's just too sparse across groupings.
